accepted = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Zlib",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "0BSD",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
